### PR TITLE
current and previous contexts are stored in a thread local variable.

### PR DESCRIPTION
**Pull request by mattcamuto**
context is now thread safe. can be used in a system like sidekiq

### CODE REVIEW

**Comment by mnelson** [comment]
Looks like we need to check for the existence of the Thread#thread_variable_set and backup to Thread.current#[] if it's not present.

**Comment by mattcamuto** [comment]
@mnelson Just saw this. We will make these changes soon to be compatible pre 2.0

**Comment by mnelson** [comment]
Great, thanks. Everything else looks good.

**Comment by mattcamuto** [comment]
@mnelson I think this is good to go all is green. Please accept if all good.

**Comment by mnelson** [comment]
Thanks so much. Merged and up at https://github.com/taskrabbit/makara/releases/tag/v0.3.3

**Pull request merged**
