### PR TITLE
Add specs

### PR DESCRIPTION
**Pull request by anthonyalberto**
Make existing ones pass

### CODE REVIEW

**Comment by anthonyalberto** [comment]
Whoops, disregard, was intended to be a PR on our fork :)

**Comment by bleonard** [comment]
anything that should be contributed back?

**Comment by anthonyalberto** [comment]
It's probably a bit rough given that some stuff has been tailored to our needs but I'll list what was done there : 
- Let the same user be able to do more than one http request that sticks to master (until the end of ttl). We had problems with ajax queries that would just make the next query stop sticking to master.
- Send back a custom http header as well as the cookie for mobile app support
- Implement `force_slave` and `force_master` methods that allows at any point in time to bypass the `needs_master?` logic and just force the pool. Sometimes we just need to send specific queries to slave.
- Add a Sidekiq middleware that cleans up context between jobs
- Stop using a server-side data-store and just rely on cookie/header for the TTL. Value of cookie now therefore includes the TTL.

Anything in particular that would be of interest?

**Comment by bleonard** [comment]
The cookie thing (`stick_to_master_until`) be relevant based on what I've heard. For example, this issue: https://github.com/taskrabbit/makara/issues/99

**Pull request closed without merging**
