### PR TITLE
Add postgis support

### PR DESCRIPTION
**Pull request by choubacha**
PostGIS is a very common extension for postgres for almost any company using locations and maps. It has it's own adapter which helps with the data typing of the geometries and preparing the database for postgis.

I've built a wrapper around the PostGIS adapter in the same vain as the postgresql adapter and written similar tests. For the tests, however, I'm only support ruby and AR 4.2+ since the postgis adapter setup is very different and prior to 4.2.

### CODE REVIEW

**Comment by lserman** [comment]
@kbacha have you used this code in production? We are in need of PostGIS read replication and considering using your code.

**Comment by bleonard** [comment]
thanks @kbacha - i know it's super delayed. this still working for you? any updates to make.

**Comment by lserman** [comment]
@bleonard I saw you mentioned this is included in 0.3.7 on the PR, but I can't seem to find the connection adapter on Github. Was it added?

**Comment by MacTynow** [comment]
@bleonard Is anybody still following this ? Is there any work that would need to be done to get this merged ?

**Comment by bleonard** [comment]
I'm open to it. I was looking for someone actually using it in production and to get the tests updated, etc. Interested in helping out?

**Comment by choubacha** [comment]
We were using it briefly and it seemed to work fine with postgix. However we had connection number issues and ended up moving to pg_pool and pg_bouncer to manage read/write segregation.

**Comment by MacTynow** [comment]
We are currently trying it out. I'll keep you updated with how it goes. @ankitagupta12, do you want to try to finish this ?

**Comment by MacTynow** [comment]
@bleonard we are now using it in production since yesterday and things seem to be working fine. We just had an issue with the [activerecord-import gem](https://github.com/zdennis/activerecord-import) that we fixed by adding a custom adapter. I will try to find the time to work on this but I'm not the greatest ruby guy.

**Comment by bleonard** [comment]
Great! The travis setiup has been updated since then. Can someone rebase from master and fix it up?

**Comment by choubacha** [comment]
@bleonard I'll take a stab real quick.

**Comment by choubacha** [comment]
@bleonard Resolved the conflicts.

**Comment by bleonard** [comment]
Merged! And shipped! Thanks for the long journey.
https://rubygems.org/gems/makara/versions/0.3.9

**Pull request merged**
