### PR TITLE
railtie initialization support for rails5

### PR DESCRIPTION
**Pull request by jonnymacs**
couldn't get a new rails 5 app to start without this change

### CODE REVIEW

**Comment by bleonard** [comment]
can anyone confirm this works in other versions of rails?

**Comment by jonnymacs** [comment]
@bleonard thnx.  Sorry wasn't able to verify backward compatabilty yet.  Assume you did?  If not I can do it this afternoon.

**Comment by bleonard** [comment]
i merged it in to master and am going to do a RC on your 4.x app next week from that and other fixes.
I'm happy for you to check, though. Can't hurt to get a few eyes on it.
Thanks

**Comment by jonnymacs** [comment]
ok, I tested this change with the rails 4.2.2 version of leagueheads.com and it worked.  Also created an empty rails 4.0.13 project then included this version of makara and I am able to initialize and run the rails console.  So I think it's safely backward compatible at least with rails4.

**Comment by bleonard** [comment]
great, @jonnymacs. thanks so much!

**Comment by bleonard** [comment]
included in release candidate. https://github.com/taskrabbit/makara/releases/tag/v0.3.7.rc

**Pull request merged**
