### PR TITLE
Handle url config for makara connections

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by mnelson** [comment]
Nice, thanks!

**Comment by mnelson** [comment]
Oops, didn't notice that most versions were broken. Mind taking a look at those tests?

**Comment by mnelson** [comment]
https://travis-ci.org/taskrabbit/makara/builds/82242328

**Comment by bf4** [comment]
Working on it... :)

B mobile phone

**Comment by bf4** [comment]
@mnelson updated and pushed.  Would you like a new PR for that (assuming it passes, which I expect it to).

**Comment by bf4** [comment]
Made a followup PR https://github.com/taskrabbit/makara/pull/94

**Pull request merged**
